[build]
  publish = "public"
  command = "npm run build"

# Config for Github pull requests.
[context.deploy-preview]
  command = "npm run build:development"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.58"
  HUGO_ENV = "development"

# Default config for branch deploys.
[context.branch-deploy]
  command = "npm run build:development"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.58"
  HUGO_ENV = "development"

# Production config.
[context.production]
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.58"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
